# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BROWN = (139, 69, 19)
DARK_BLUE = (0, 0, 139)
PURPLE = (128, 0, 128)
ORANGE = (255, 165, 0)
YELLOW = (255, 255, 0)
LIGHT_BLUE = (173, 216, 230)
GREY = (128, 128, 128)

# --- SIZING ---
# These values control the global scale of the game elements.
# Adjust these to change the size of the objects on the map.
TOWER_SIZE = (180, 180)
TOWER_Y_OFFSET = -60 # Negative to move up
PLOT_SIZE = (100, 100) # Should be smaller than towers to create a base effect
PATH_WIDTH = 80
BARRICADE_SIZE = (40, 40)
CASTLE_SIZE = (200, 200)
SPAWN_GATE_SIZE = (60, 60)
CASTLE_Y_OFFSET = -140 # Negative to move up
CASTLE_SIZE = (800,400)
SPAWN_GATE_SIZE = (200, 220)

# --- UI SIZING ---
HUD_PANEL_WIDTH = 250
SHOP_PANEL_WIDTH = 300
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 50
HEALTH_BAR_WIDTH = HUD_PANEL_WIDTH - 40
HEALTH_BAR_HEIGHT = 30
HEALTH_BAR_Y = 70
SHOP_CARD_HEIGHT = 60
SHOP_CARD_Y_START = 120
SHOP_CARD_ICON_SIZE = (40, 40)
ABILITY_ICON_SIZE = (50, 50)
OVERCHARGE_Y_OFFSET = 140
AOE_Y_OFFSET = 70

# --- FONT SIZES ---
FONT_SIZE_NORMAL = 36
FONT_SIZE_TITLE = 72
FONT_SIZE_TOOLTIP = 24

# --- UI PADDING & MARGINS ---
HUD_PADDING = 20
SHOP_PADDING = 20
BUTTON_MARGIN = 10

# --- SETTINGS MENU POSITIONS & SIZES ---
SETTINGS_TITLE_Y = 100
SETTINGS_MUSIC_Y = 250
SETTINGS_SFX_Y = 300
SETTINGS_BACK_BUTTON_Y = 400
SETTINGS_LEVEL_SELECT_Y = 470
SETTINGS_BUTTON_SIZE = (30, 30)
SETTINGS_BUTTON_SPACING = 20
FF_BUTTON_Y_OFFSET = 70
SETTINGS_BUTTON_Y_OFFSET = 140

# Tower settings
SUNFIRE_SPIRE_COST = 100
SUNFIRE_SPIRE_RANGE = 200 # Increased range to match new scale
SUNFIRE_SPIRE_DAMAGE = 12
SUNFIRE_SPIRE_FIRE_RATE = 1 * FPS # Once per second

FROST_SPIRE_COST = 150
FROST_SPIRE_RANGE = 160 # Increased range to match new scale
FROST_SPIRE_DAMAGE = 10
FROST_SPIRE_FIRE_RATE = 1.5 * FPS # Slower fire rate
FROST_SPIRE_SLOW_DURATION = 2 * FPS
FROST_SPIRE_SLOW_FACTOR = 0.5

STORM_SPIRE_COST = 200
STORM_SPIRE_RANGE = 180 # Increased range to match new scale
STORM_SPIRE_DAMAGE = 10
STORM_SPIRE_FIRE_RATE = 2 * FPS
STORM_SPIRE_AOE_RADIUS = 90

# Enemy settings
ENEMY_ATTACK_DAMAGE = 10
ENEMY_ATTACK_RATE = 1 * FPS
SHADOW_CRAWLER_HEALTH = 100
SHADOW_CRAWLER_SPEED = 2
SHADOW_CRAWLER_VALUE = 10
SHADOW_CRAWLER_SIZE = (60, 60)

SHADOW_FLYER_HEALTH = 70
SHADOW_FLYER_SPEED = 3
SHADOW_FLYER_VALUE = 15
SHADOW_FLYER_SIZE = (60, 60)

SHIELDING_SENTINEL_HEALTH = 150
SHIELDING_SENTINEL_SHIELD = 100
SHIELDING_SENTINEL_SPEED = 1.5
SHIELDING_SENTINEL_VALUE = 20
SHIELDING_SENTINEL_SIZE = (60, 60)
SHIELDING_SENTINEL_COOLDOWN = 5 * FPS # 5 seconds

CHRONO_WARPER_HEALTH = 80
CHRONO_WARPER_SPEED = 2.5
CHRONO_WARPER_VALUE = 25
CHRONO_WARPER_SIZE = (60, 60)
CHRONO_WARPER_PULSE_RATE = 4 * FPS
CHRONO_WARPER_PULSE_RADIUS = 150
CHRONO_WARPER_SLOW_DURATION = 3 * FPS
CHRONO_WARPER_SLOW_FACTOR = 0.5 # Halves tower fire rate

SABOTEUR_HEALTH = 90
SABOTEUR_SPEED = 3.5
SABOTEUR_VALUE = 30
SABOTEUR_SIZE = (60, 60)
SABOTEUR_DISABLE_DURATION = 4 * FPS

HEALER_HEALTH = 60
HEALER_SPEED = 2
HEALER_VALUE = 35
HEALER_SIZE = (60, 60)
HEALER_PULSE_RATE = 3 * FPS
HEALER_PULSE_RADIUS = 100
HEALER_HEAL_AMOUNT = 10

# Tactical Abilities
SPIRE_PLOT_COST = 150 # Permanent currency
BARRICADE_COST = 25 # Temporary currency
BARRICADE_HEALTH = 250
BARRICADE_DURATION = 15 * FPS # 15 seconds
OVERCHARGE_COST = 50
OVERCHARGE_DURATION = 5 * FPS
OVERCHARGE_MULTIPLIER = 2.0 # Double damage
AOE_ATTACK_COST = 75
AOE_ATTACK_RADIUS = 100
AOE_ATTACK_DAMAGE = 150

# Currency settings
VOLATILE_TO_META_CONVERSION_RATIO = 1.0

# Level data is now in levels.py