# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BROWN = (139, 69, 19)
DARK_BLUE = (0, 0, 139)
PURPLE = (128, 0, 128)
ORANGE = (255, 165, 0)
YELLOW = (255, 255, 0)
LIGHT_BLUE = (173, 216, 230)
GREY = (128, 128, 128)

# Tower settings
SUNFIRE_SPIRE_COST = 100
SUNFIRE_SPIRE_RANGE = 150
SUNFIRE_SPIRE_DAMAGE = 12
SUNFIRE_SPIRE_FIRE_RATE = 1 * FPS # Once per second

FROST_SPIRE_COST = 150
FROST_SPIRE_RANGE = 120
FROST_SPIRE_DAMAGE = 10
FROST_SPIRE_FIRE_RATE = 1.5 * FPS # Slower fire rate
FROST_SPIRE_SLOW_DURATION = 2 * FPS
FROST_SPIRE_SLOW_FACTOR = 0.5

STORM_SPIRE_COST = 200
STORM_SPIRE_RANGE = 140
STORM_SPIRE_DAMAGE = 10
STORM_SPIRE_FIRE_RATE = 2 * FPS
STORM_SPIRE_AOE_RADIUS = 90

# Enemy settings
ENEMY_ATTACK_DAMAGE = 10
ENEMY_ATTACK_RATE = 1 * FPS
SHADOW_CRAWLER_HEALTH = 100
SHADOW_CRAWLER_SPEED = 2
SHADOW_CRAWLER_VALUE = 10

SHADOW_FLYER_HEALTH = 70
SHADOW_FLYER_SPEED = 3
SHADOW_FLYER_VALUE = 15

SHIELDING_SENTINEL_HEALTH = 150
SHIELDING_SENTINEL_SHIELD = 100
SHIELDING_SENTINEL_SPEED = 1.5
SHIELDING_SENTINEL_VALUE = 20
SHIELDING_SENTINEL_COOLDOWN = 5 * FPS # 5 seconds

CHRONO_WARPER_HEALTH = 80
CHRONO_WARPER_SPEED = 2.5
CHRONO_WARPER_VALUE = 25
CHRONO_WARPER_PULSE_RATE = 4 * FPS
CHRONO_WARPER_PULSE_RADIUS = 150
CHRONO_WARPER_SLOW_DURATION = 3 * FPS
CHRONO_WARPER_SLOW_FACTOR = 0.5 # Halves tower fire rate

SABOTEUR_HEALTH = 90
SABOTEUR_SPEED = 3.5
SABOTEUR_VALUE = 30
SABOTEUR_DISABLE_DURATION = 4 * FPS

# Tactical Abilities
SPIRE_PLOT_COST = 150 # Permanent currency
BARRICADE_COST = 25 # Temporary currency
BARRICADE_HEALTH = 250
OVERCHARGE_COST = 50
OVERCHARGE_DURATION = 5 * FPS
OVERCHARGE_MULTIPLIER = 2.0 # Double damage
AOE_ATTACK_COST = 75
AOE_ATTACK_RADIUS = 100
AOE_ATTACK_DAMAGE = 150

# Level data is now in levels.py